import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Bar() {
  return (
    <>
      <Head>
        <title>Barページ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        Barページ
        <Link href="/foo/1">前のページへ</Link>
        <Link href="/foo/bar/1/slug/1">次のページへ</Link>
      </main>
    </>
  )
}