name: Check for Differences with develop

on:
  workflow_dispatch:

jobs:
  check_diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch all branches
        run: git fetch --all

      - name: Check if base branch is merged into development branch
        run: |
          git merge-base --is-ancestor origin/main HEAD
          if [ $? -ne 0 ]; then
            echo "baseブランチとの差分があります。最新のmainブランチをマージしてください"
            exit 1
          else
            echo "baseブランチとの差分はありません"
          fi

      - name: Send Slack notification
        if: failure()
        run: |
          echo "baseブランチとの差分があります。最新のmainブランチをマージしてください"