name: Check for Differences with develop

on:
  workflow_dispatch:

jobs:
  check_diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch all branches
        run: git fetch origin

      - name: Check if base branch is merged into development branch
        run: |
          if ! git merge-base --is-ancestor origin/main HEAD; then
            echo "ERROR: HEAD is not based on upstream HEAD"
            exit 1
          fi

      - name: Send Slack notification
        if: failure()
        run: |
          echo "baseブランチとの差分があります。最新のmainブランチをマージしてください"