name: Check for Differences with develop

on:
  workflow_dispatch:

jobs:
  check_diff:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fetch all branches
      run: git fetch --all

    - name: Check for differences with main branch
      run: |
        if ! git diff --quiet origin/main; then
          echo "baseブランチとの差分があります。最新のmainブランチをマージしてください"
          exit 1
        else
          echo "baseブランチとの差分はありません"
        fi